ActionManager {
 Actions {
  Action VRMVoiceRangeDecrease {
   InputSource InputSourceSum "{69BB52A0CFBAA340}" {
    Sources {
     InputSourceValue "{69BB52A0CFBAA341}" {
      FilterPreset "click"
      Input "keyboard:KC_F4"
      Filter InputFilterClick "{69BB52A0CFBAA346}" {
      }
     }
     InputSourceEmpty "{69BB52A0CFBAA342}" {
      FilterPreset "gamepad:click"
      DeviceType GAMEPAD
     }
    }
   }
  }
  Action VRMVoiceRangeIncrease {
   InputSource InputSourceSum "{69BB52A0CFBAA343}" {
    Sources {
     InputSourceValue "{69BB52A0CFBAA344}" {
      FilterPreset "click"
      Input "keyboard:KC_F5"
      Filter InputFilterClick "{69BB52A0CFBAA347}" {
      }
     }
     InputSourceEmpty "{69BB52A0CFBAA345}" {
      FilterPreset "gamepad:click"
      DeviceType GAMEPAD
     }
    }
   }
  }
 }
 Contexts {
  ActionContext CharacterGeneralContext {
   ActionRefs +{
    "VRMVoiceRangeDecrease"
    "VRMVoiceRangeIncrease"
   }
  }
  ActionContext CharacterMovementContext {
   ActionRefs +{
    "VRMVoiceRangeDecrease"
    "VRMVoiceRangeIncrease"
   }
  }
 }
}
