ActionManager {
 Actions {
  Action NVRVoiceRangeDecrease {
   InputSource InputSourceSum "{72A331E1AB7C4101}" {
    Sources {
     InputSourceValue "{72A331E1AB7C4102}" {
      FilterPreset "click"
      Input "keyboard:KC_F3"
      Filter InputFilterClick "{72A331E1AB7C4103}" {
      }
     }
     InputSourceCombo "{72A331E1AB7C4104}" {
      FilterPreset "gamepad:click"
      Sources {
       InputSourceValue "{72A331E1AB7C4105}" {
        Input "gamepad0:shoulder_right"
       }
       InputSourceValue "{72A331E1AB7C4106}" {
        Input "gamepad0:pad_down"
        Filter InputFilterClick "{72A331E1AB7C4107}" {
        }
       }
      }
     }
    }
   }
  }
  Action NVRVoiceRangeIncrease {
   InputSource InputSourceSum "{72A331E1AB7C4111}" {
    Sources {
     InputSourceValue "{72A331E1AB7C4112}" {
      FilterPreset "click"
      Input "keyboard:KC_F4"
      Filter InputFilterClick "{72A331E1AB7C4113}" {
      }
     }
     InputSourceCombo "{72A331E1AB7C4114}" {
      FilterPreset "gamepad:click"
      Sources {
       InputSourceValue "{72A331E1AB7C4115}" {
        Input "gamepad0:shoulder_right"
       }
       InputSourceValue "{72A331E1AB7C4116}" {
        Input "gamepad0:pad_up"
        Filter InputFilterClick "{72A331E1AB7C4117}" {
        }
       }
      }
     }
    }
   }
  }
  Action NVRVoiceRangeToggleHUD {
   InputSource InputSourceSum "{72A331E1AB7C4131}" {
    Sources {
     InputSourceValue "{72A331E1AB7C4132}" {
      FilterPreset "click"
      Input "keyboard:KC_F5"
      Filter InputFilterClick "{72A331E1AB7C4133}" {
      }
     }
     InputSourceCombo "{72A331E1AB7C4134}" {
      FilterPreset "gamepad:click"
      Sources {
       InputSourceValue "{72A331E1AB7C4135}" {
        Input "gamepad0:shoulder_right"
       }
       InputSourceValue "{72A331E1AB7C4136}" {
        Input "gamepad0:pad_right"
        Filter InputFilterClick "{72A331E1AB7C4137}" {
        }
       }
      }
     }
    }
   }
  }
 }
 Contexts {
  ActionContext CharacterGeneralContext {
   ActionRefs +{
    "NVRVoiceRangeDecrease"
    "NVRVoiceRangeIncrease"
    "NVRVoiceRangeToggleHUD"
   }
  }
  ActionContext CharacterMovementContext {
   ActionRefs +{
    "NVRVoiceRangeDecrease"
    "NVRVoiceRangeIncrease"
    "NVRVoiceRangeToggleHUD"
   }
  }
 }
}
