SCR_KeyBindingMenuConfig {
 m_KeyBindingCategories {
  SCR_KeyBindingCategory "{72A331E1AB7C4121}" {
   m_sName "VoiceRange"
   m_sDisplayName "Voice Range Settings"
   m_KeyBindingEntries {
    SCR_KeyBindingEntry "{72A331E1AB7C4122}" {
     m_sActionName "NVRVoiceRangeDecrease"
     m_sActionNameGamepadOptional "NVRVoiceRangeDecrease"
     m_sDisplayName "Decrease Voice Range"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{72A331E1AB7C4123}" {
     m_sActionName "NVRVoiceRangeIncrease"
     m_sActionNameGamepadOptional "NVRVoiceRangeIncrease"
     m_sDisplayName "Increase Voice Range"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{72A331E1AB7C4124}" {
     m_sActionName "NVRVoiceRangeToggleHUD"
     m_sActionNameGamepadOptional "NVRVoiceRangeToggleHUD"
     m_sDisplayName "Toggle Voice Range HUD"
     m_sPreset "click"
    }
   }
  }
 }
}
