SCR_KeyBindingMenuConfig {
 m_KeyBindingCategories {
  SCR_KeyBindingCategory "{69BB52A0CFBAA350}" {
   m_sName "VoiceRange"
   m_sDisplayName "Voice Range"
   m_KeyBindingEntries {
    SCR_KeyBindingEntry "{69BB52A0CFBAA351}" {
     m_sActionName "VRMVoiceRangeDecrease"
     m_sActionNameGamepadOptional "VRMVoiceRangeDecrease"
     m_sDisplayName "Decrease Voice Range"
     m_sPreset "click"
    }
    SCR_KeyBindingEntry "{69BB52A0CFBAA352}" {
     m_sActionName "VRMVoiceRangeIncrease"
     m_sActionNameGamepadOptional "VRMVoiceRangeIncrease"
     m_sDisplayName "Increase Voice Range"
     m_sPreset "click"
    }
   }
  }
 }
}
